Models/Company.cs
/*
Filename:  Company.cs
Purpose:   Provide a structure for Company objects  
Contains:  Class properties and data annotations to implement business requirements  
Author:    Martin Dwyer
Created:   2022-08-17
Last Edit: 2022-08-23
By:        Martin Dwyer
*/

using Microsoft.Build.Framework;

namespace CC.Reads.Models
{
    public class Company
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        public string? StreetAddress { get; set; }

        public string? City { get; set; }

        public string? State { get; set; }

        public string? PostalCode { get; set; }

        public string? PhoneNumber { get; set; }

    }
}

Areas/Admin/Controllers/CompaniesController.cs
/*
Filename:  CompaniesController.cs
Purpose:   Control requests related to Company objects
Contains:  GET and POST actions methods to create, retrieve, update and delete companies
Author:    Martin Dwyer
Created:   2022-08-17
Last Edit: 2022-08-19
By:        Martin Dwyer
*/
using CC.Reads.DataAccess.Repository.Interface;
using CC.Reads.Models;
using Microsoft.AspNetCore.Mvc;

namespace CC.Reads.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CompaniesController : Controller
    {
        private readonly IUnitOfWork _context; // Adding Db context property

        /**
         * Constructor requires a live ApplicationDbContext from the repository
        */
        public CompaniesController(IUnitOfWork context)
        {
            _context = context;

        }


        /**
         * Action method to GET Company objects.  Takes in no parameters.  Is async to wait
         * for data retrieval. 
         *
         * Returns a View with a list of Company objects.
        */
        public IActionResult Index()
        {

            return View();
        }


        /**
         * Details(int) action method handles a GET request for Company details.  The method accepts 
         * an integer, retrieves the company object from the database, and sends the object to a view 
         * where it is displayed.
         * 
         * param id the unique identifier of the Company object
         * returns a View with the category object          
        */
        public IActionResult Details(int? id)
        {

            var obj = _context.Company.GetFirstOrDefault(m => m.Id == id, "");
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }


        /**
         * Upsert(int id) handles a GET request to update or insert a Company object with id as the
         * unique identifier for the object.  The method checks to see if the Company object can be found with 
         * the provided id.  If found, a View is presented with the Company object information.  If not found,
         * a View is presented with an empty Company object.
         * 
         * param id, an int, is the unique identifier for the Company object
         * returns a View with the Company object if found in the Db
         * returns a View with an empty Company object if not found in the Db
        */
        public IActionResult Upsert(int? id)
        {
            Company company = new();

            // If id not provided or 0, return a View with the empty company object
            if (id == null || id == 0)
            {
                return View(company);
            }
            else
            {
                // Otherwise, return a view with the company object found
                company = _context.Company.GetFirstOrDefault(u => u.Id == id, "");

                return View(company);
            }

        }


        /**
         * Upsert(Company company) handles a POST request to update or insert a Company object.
         * The method handles Model validation and either creates or updates a Company object as appropriate.
         * 
         * param company, a Company object to be inserted or updated  
         * returns a View with a list of all Company objects
        */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Company company)
        {

            if (company.Id == 0)
            {
                _context.Company.Add(company);
                TempData["success"] = "Company created successfully";
            }
            else
            {
                _context.Company.Update(company);
                TempData["success"] = "Company updated successfully";
            }

            _context.Save();

            return RedirectToAction("Index");

        }

        /*
         * API end points allow the developer to create, retrieve, update or delete data 
         * in the Db without updating the Page or View.  
         */
        #region API CALLS
        
        /**
         * GetAll() handles a GET request for all objects.  It returns all Company objects in
         * Json format.
         */
        [HttpGet]
        public IActionResult GetAll()
        {
            var companyList = _context.Company.GetAll();
            return Json(new { data = companyList });

        }

        /**
         * Delete(int id) handles a POST request to delete Company object with unique identifier of
         * id.  If successful, a Json object is returned indicating the object was deleted
         */
        [HttpDelete]
        public IActionResult Delete(int id)
        {

            var obj = _context.Company.GetFirstOrDefault(m => m.Id == id, "");

            _context.Company.Remove(obj);
            _context.Save();


            return Json(new { success = true, message = "Delete successful" });
        }

        #endregion
    }



}

Areas/Admin/Views/Companies/Details.cshtml
@*
Filename:  Details.cshtml
Purpose:   View for displaying details for Company objects
Contains:  Model, ViewData for page title, Layout specification, Html, asp tag helpers, JavaScript
Author:    Martin Dwyer
Created:   2022-08-17
Last Edit: 2022-08-22
By:        Martin Dwyer
*@

@model CC.Reads.Models.Company

@{
    ViewData["Title"] = "Company Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">

    <h1 class="mt-5">@ViewData["Title"]</h1>

    <div>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Id)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Id)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.StreetAddress)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.StreetAddress)
            </dd>

            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.City)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.City)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.State)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.State)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PostalCode)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PostalCode)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PhoneNumber)
            </dd>

        </dl>
    </div>
    <div>
        <a asp-action="Upsert" asp-route-id="@Model?.Id" class="btn btn-primary">Edit</a> &nbsp;
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </div>
</div>

Areas/Admin/Views/Companies/Index.cshtml
@*
Filename:  Index.cshtml
Purpose:   View for displaying all Company objects and offering options to create, update and delete Companies. 
Contains:  Model, ViewData for page title, Layout specification, Html, asp tag helpers, JavaScript
Author:    Martin Dwyer
Created:   2022-08-17
Last Edit: 2022-08-22
By:        Martin Dwyer
*@

@model IEnumerable<CC.Reads.Models.Company>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">

    <h1 class="mt-5">Companies</h1>
    <partial name="_Notification"/>
    <p>
        <a asp-controller="Companies" asp-action="Upsert" class="btn btn-success mb-3">Create New</a>
    </p>
    <table class="table" id="productData" style="width:100%">
        <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StreetAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PostalCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th></th>
        </tr>
        </thead>
    </table>
</div>

@section Scripts {
    <script src="~/js/company.js"></script>
}

Areas/Admin/Views/Companies/Upsert.cshtml
@*
Filename:  Upsert.cshtml
Purpose:   View for creating (inserting) or updating Company objects
Contains:  Model, ViewData for page title, Layout specification, Html, asp tag helpers, JavaScript
Author:    Martin Dwyer
Created:   2022-08-17
Last Edit: 2022-08-22
By:        Martin Dwyer
*@

@model CC.Reads.Models.Company

@{
    ViewData["Title"] = "Upsert";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">

    <h1 class="mt-5">@(Model.Id !=0 ? "Update" : "Create") Company</h1>

    <h4></h4>
    <hr />
    <style>
        .form-group {
            margin-bottom: 1rem;
        }
    </style>


    <div class="row">
        <div class="col-10">

            <form asp-action="Upsert" style="width: 100%;" enctype="multipart/form-data">
                <div class="row">



                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="@Model.Id" />

                    <div class="form-group">
                        <label asp-for="@Model.Name" class="control-label"></label>
                        <input asp-for="@Model.Name" class="form-control" />
                        <span asp-validation-for="@Model.Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.StreetAddress" class="control-label"></label>
                        <input asp-for="@Model.StreetAddress" class="form-control" rows="8" />
                        <span asp-validation-for="@Model.StreetAddress" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.City" class="control-label"></label>
                        <input asp-for="@Model.City" class="form-control" />
                        <span asp-validation-for="@Model.City" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.State" class="control-label"></label>
                        <input asp-for="@Model.State" class="form-control" />
                        <span asp-validation-for="@Model.State" class="text-danger"></span>
                    </div>


                    <div class="form-group">
                        <label asp-for="@Model.PostalCode" class="control-label"></label>
                        <input asp-for="@Model.PostalCode" class="form-control" />
                        <span asp-validation-for="@Model.PostalCode" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="@Model.PhoneNumber" class="control-label"></label>
                        <input asp-for="@Model.PhoneNumber" class="form-control" />
                        <span asp-validation-for="@Model.PhoneNumber" class="text-danger"></span>
                    </div>

                </div>
                <div class="row">
                    @if (Model.Id != 0)
                    {
                        <input type="submit" value="Update" class="btn btn-primary" style="width: 150px;" />
                    }
                    else
                    {
                        <input type="submit" value="Create" class="btn btn-primary" style="width: 150px;" />
                    }

                    <a asp-action="Index" class="btn btn-secondary" style="width: 150px; float: left; margin-left: 2rem;">Back to List</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />

    }


}